project:
  type: website
  output-dir: docs
  render:
    # - "notebooks/genx-results-scenarios-all.qmd"
    # - "notebooks/genx-results-scenarios-10-days.qmd"
    # - "notebooks/genx-results-scenarios-20-weeks.qmd"

    - "genx-notebooks/genx-results-scenarios.qmd"
    
    # - "genx-notebooks/genx-results-scenarios-10-days.qmd"
    # - "genx-notebooks/genx-results-scenarios-20-weeks.qmd"
    # - "*.qmd"


website:
  title: "Genx-NY-MIP"
  # navbar:
  #   left:
      # - text: "All Scenarios"
      #   href: notebooks/genx-results-scenarios-all.qmd
      # - text: "10-day Scenarios"
      #   href: notebooks/genx-results-scenarios-10-days.qmd
      # - text: "20-Week Scenarios"
      #   href: notebooks/genx-results-scenarios-20-weeks.qmd     
      # - text: "GenX Scenarios"
      #   href: genx-notebooks/genx-results-scenarios.qmd
        
      # - text: "10-day Scenarios"
      #   href: genx-notebooks/genx-results-scenarios-10-days.qmd
      # - text: "20-Week Scenarios"
      #   href: genx-notebooks/genx-results-scenarios-20-weeks.qmd
      # - blog.qmd
      # - about.qmd
      # - text: Cars
      #   href: posts/other-notebook.ipynb
      # - text: Analysis
      #   href: posts/hello-penguins.ipynb
      
# execute:
#   cache: true
#   cache-dir: _cache

format:
  dashboard:
    theme: default
    # scrolling: false
    # embed-resources: true          # embed all resources in HTML files
    # self-contained: true           # create self-contained HTML files
    # lib-dir: libs                   # put JS/CSS libs in _site/libs/
    # fig-format: svg                # use SVG for vector graphics
    # fig-dpi: 96                   # standard DPI for good quality